# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'guiv1.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtCore import QObject, pyqtSlot
from PyQt5.QtWidgets import QTableWidget, QTableWidgetItem
from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(QObject):  
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(868, 675)
        MainWindow.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        MainWindow.setLayoutDirection(QtCore.Qt.LeftToRight)
        MainWindow.setAutoFillBackground(False)
        MainWindow.setTabShape(QtWidgets.QTabWidget.Rounded)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.stackedWidget = QtWidgets.QStackedWidget(self.centralwidget)
        self.stackedWidget.setGeometry(QtCore.QRect(50, 10, 801, 631))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setStrikeOut(False)
        font.setKerning(True)
        self.stackedWidget.setFont(font)
        self.stackedWidget.setObjectName("stackedWidget")
        self.page_6 = QtWidgets.QWidget()
        self.page_6.setObjectName("page_6")
        self.label_19 = QtWidgets.QLabel(self.page_6)
        self.label_19.setGeometry(QtCore.QRect(170, 70, 421, 91))
        font = QtGui.QFont()
        font.setFamily("Serif")
        font.setPointSize(50)
        font.setBold(True)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(75)
        self.label_19.setFont(font)
        self.label_19.setObjectName("label_19")
        self.label_20 = QtWidgets.QLabel(self.page_6)
        self.label_20.setGeometry(QtCore.QRect(330, 150, 111, 91))
        font = QtGui.QFont()
        font.setFamily("Serif")
        font.setPointSize(50)
        font.setBold(True)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(75)
        self.label_20.setFont(font)
        self.label_20.setObjectName("label_20")
        self.label_21 = QtWidgets.QLabel(self.page_6)
        self.label_21.setGeometry(QtCore.QRect(110, 220, 551, 91))
        font = QtGui.QFont()
        font.setFamily("Serif")
        font.setPointSize(45)
        font.setBold(True)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(75)
        self.label_21.setFont(font)
        self.label_21.setObjectName("label_21")
        self.pushButton_3 = QtWidgets.QPushButton(self.page_6)
        self.pushButton_3.setGeometry(QtCore.QRect(340, 440, 101, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(50)
        self.pushButton_3.setFont(font)
        self.pushButton_3.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_3.setObjectName("pushButton_3")
        self.get_started_btn = QtWidgets.QPushButton(self.page_6)
        self.get_started_btn.setGeometry(QtCore.QRect(100, 320, 591, 51))
        font = QtGui.QFont()
        font.setFamily("Serif")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.get_started_btn.setFont(font)
        self.get_started_btn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.get_started_btn.setObjectName("get_started_btn")
        self.history_btn = QtWidgets.QPushButton(self.page_6)
        self.history_btn.setGeometry(QtCore.QRect(100, 380, 591, 51))
        font = QtGui.QFont()
        font.setFamily("Serif")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.history_btn.setFont(font)
        self.history_btn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.history_btn.setObjectName("history_btn")
        self.stackedWidget.addWidget(self.page_6)
        self.page = QtWidgets.QWidget()
        self.page.setObjectName("page")
        self.nextButton = QtWidgets.QPushButton(self.page)
        self.nextButton.setGeometry(QtCore.QRect(560, 320, 131, 31))
        self.nextButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.nextButton.setObjectName("nextButton")
        self.label_22 = QtWidgets.QLabel(self.page)
        self.label_22.setGeometry(QtCore.QRect(100, 0, 571, 91))
        font = QtGui.QFont()
        font.setFamily("Serif")
        font.setPointSize(35)
        font.setBold(True)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(75)
        self.label_22.setFont(font)
        self.label_22.setObjectName("label_22")
        self.home_btn2 = QtWidgets.QPushButton(self.page)
        self.home_btn2.setGeometry(QtCore.QRect(70, 320, 121, 31))
        self.home_btn2.setObjectName("home_btn2")
        self.frame = QtWidgets.QFrame(self.page)
        self.frame.setGeometry(QtCore.QRect(60, 110, 636, 108))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.label = QtWidgets.QLabel(self.frame)
        self.label.setGeometry(QtCore.QRect(190, 10, 261, 24))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.layoutWidget = QtWidgets.QWidget(self.frame)
        self.layoutWidget.setGeometry(QtCore.QRect(10, 70, 168, 30))
        self.layoutWidget.setObjectName("layoutWidget")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.cancelButton = QtWidgets.QPushButton(self.layoutWidget)
        self.cancelButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.cancelButton.setObjectName("cancelButton")
        self.horizontalLayout_2.addWidget(self.cancelButton)
        self.importButton = QtWidgets.QPushButton(self.layoutWidget)
        self.importButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.importButton.setObjectName("importButton")
        self.horizontalLayout_2.addWidget(self.importButton)
        self.layoutWidget1 = QtWidgets.QWidget(self.frame)
        self.layoutWidget1.setGeometry(QtCore.QRect(10, 42, 611, 25))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.layoutWidget1)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_2 = QtWidgets.QLabel(self.layoutWidget1)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout.addWidget(self.label_2)
        self.pathLine = QtWidgets.QLineEdit(self.layoutWidget1)
        self.pathLine.setObjectName("pathLine")
        self.horizontalLayout.addWidget(self.pathLine)
        self.browseButton = QtWidgets.QPushButton(self.layoutWidget1)
        self.browseButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.browseButton.setObjectName("browseButton")
        self.horizontalLayout.addWidget(self.browseButton)
        self.frame_2 = QtWidgets.QFrame(self.page)
        self.frame_2.setGeometry(QtCore.QRect(70, 230, 621, 80))
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.layoutWidget2 = QtWidgets.QWidget(self.frame_2)
        self.layoutWidget2.setGeometry(QtCore.QRect(101, 50, 401, 22))
        self.layoutWidget2.setObjectName("layoutWidget2")
        self.gridLayout = QtWidgets.QGridLayout(self.layoutWidget2)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.radio_btn_c = QtWidgets.QRadioButton(self.layoutWidget2)
        self.radio_btn_c.setObjectName("radio_btn_c")
        self.gridLayout.addWidget(self.radio_btn_c, 0, 0, 1, 1)
        self.radio_btn_r = QtWidgets.QRadioButton(self.layoutWidget2)
        self.radio_btn_r.setObjectName("radio_btn_r")
        self.gridLayout.addWidget(self.radio_btn_r, 0, 1, 1, 1)
        self.radio_btn_ts = QtWidgets.QRadioButton(self.layoutWidget2)
        self.radio_btn_ts.setObjectName("radio_btn_ts")
        self.gridLayout.addWidget(self.radio_btn_ts, 0, 2, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.frame_2)
        self.label_3.setGeometry(QtCore.QRect(160, 10, 291, 24))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.stackedWidget.addWidget(self.page)
        self.page_2 = QtWidgets.QWidget()
        self.page_2.setObjectName("page_2")
        self.backButton1 = QtWidgets.QPushButton(self.page_2)
        self.backButton1.setGeometry(QtCore.QRect(10, 560, 80, 31))
        self.backButton1.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.backButton1.setObjectName("backButton1")
        self.label_23 = QtWidgets.QLabel(self.page_2)
        self.label_23.setGeometry(QtCore.QRect(70, 0, 631, 91))
        font = QtGui.QFont()
        font.setFamily("Serif")
        font.setPointSize(35)
        font.setBold(True)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(75)
        self.label_23.setFont(font)
        self.label_23.setObjectName("label_23")
        self.describe_text_edit = QtWidgets.QTextEdit(self.page_2)
        self.describe_text_edit.setGeometry(QtCore.QRect(90, 450, 541, 141))
        self.describe_text_edit.setObjectName("describe_text_edit")
        self.label_13 = QtWidgets.QLabel(self.page_2)
        self.label_13.setGeometry(QtCore.QRect(90, 420, 221, 31))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label_13.setFont(font)
        self.label_13.setObjectName("label_13")
        self.layoutWidget3 = QtWidgets.QWidget(self.page_2)
        self.layoutWidget3.setGeometry(QtCore.QRect(90, 110, 541, 301))
        self.layoutWidget3.setObjectName("layoutWidget3")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.layoutWidget3)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.tableWidget = QtWidgets.QTableWidget(self.layoutWidget3)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(0)
        self.tableWidget.setRowCount(0)
        self.verticalLayout.addWidget(self.tableWidget)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.load_DB_btn = QtWidgets.QPushButton(self.layoutWidget3)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.load_DB_btn.setFont(font)
        self.load_DB_btn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.load_DB_btn.setObjectName("load_DB_btn")
        self.horizontalLayout_3.addWidget(self.load_DB_btn)
        self.nextButton1 = QtWidgets.QPushButton(self.layoutWidget3)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.nextButton1.setFont(font)
        self.nextButton1.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.nextButton1.setObjectName("nextButton1")
        self.horizontalLayout_3.addWidget(self.nextButton1)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.label_5 = QtWidgets.QLabel(self.page_2)
        self.label_5.setGeometry(QtCore.QRect(271, 81, 65, 19))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.comboBox = QtWidgets.QComboBox(self.page_2)
        self.comboBox.setGeometry(QtCore.QRect(350, 80, 79, 23))
        self.comboBox.setMaximumSize(QtCore.QSize(79, 16777215))
        self.comboBox.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.comboBox.setStyleSheet("selection-background-color: rgb(85, 255, 127);")
        self.comboBox.setObjectName("comboBox")
        self.stackedWidget.addWidget(self.page_2)
        self.page_5 = QtWidgets.QWidget()
        self.page_5.setObjectName("page_5")
        self.dbTable = QtWidgets.QTableWidget(self.page_5)
        self.dbTable.setGeometry(QtCore.QRect(22, 76, 381, 471))
        self.dbTable.setObjectName("dbTable")
        self.dbTable.setColumnCount(0)
        self.dbTable.setRowCount(0)
        self.back_btn = QtWidgets.QPushButton(self.page_5)
        self.back_btn.setGeometry(QtCore.QRect(20, 560, 80, 31))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.back_btn.setFont(font)
        self.back_btn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.back_btn.setObjectName("back_btn")
        self.label_24 = QtWidgets.QLabel(self.page_5)
        self.label_24.setGeometry(QtCore.QRect(300, 20, 241, 51))
        font = QtGui.QFont()
        font.setFamily("Serif")
        font.setPointSize(35)
        font.setBold(True)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(75)
        self.label_24.setFont(font)
        self.label_24.setObjectName("label_24")
        self.layoutWidget4 = QtWidgets.QWidget(self.page_5)
        self.layoutWidget4.setGeometry(QtCore.QRect(407, 81, 371, 461))
        self.layoutWidget4.setObjectName("layoutWidget4")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.layoutWidget4)
        self.verticalLayout_9.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.pushButton_2 = QtWidgets.QPushButton(self.layoutWidget4)
        self.pushButton_2.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_2.setObjectName("pushButton_2")
        self.verticalLayout_4.addWidget(self.pushButton_2)
        self.textEdit = QtWidgets.QTextEdit(self.layoutWidget4)
        self.textEdit.setObjectName("textEdit")
        self.verticalLayout_4.addWidget(self.textEdit)
        self.verticalLayout_9.addLayout(self.verticalLayout_4)
        self.verticalLayout_7 = QtWidgets.QVBoxLayout()
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.showen_btn = QtWidgets.QPushButton(self.layoutWidget4)
        self.showen_btn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.showen_btn.setObjectName("showen_btn")
        self.verticalLayout_7.addWidget(self.showen_btn)
        self.predict_btn = QtWidgets.QPushButton(self.layoutWidget4)
        self.predict_btn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.predict_btn.setObjectName("predict_btn")
        self.verticalLayout_7.addWidget(self.predict_btn)
        self.verticalLayout_9.addLayout(self.verticalLayout_7)
        self.stackedWidget.addWidget(self.page_5)
        self.page_3 = QtWidgets.QWidget()
        self.page_3.setObjectName("page_3")
        self.label_15 = QtWidgets.QLabel(self.page_3)
        self.label_15.setGeometry(QtCore.QRect(370, 90, 211, 21))
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.label_15.setFont(font)
        self.label_15.setObjectName("label_15")
        self.groupBox = QtWidgets.QGroupBox(self.page_3)
        self.groupBox.setGeometry(QtCore.QRect(90, 90, 174, 441))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.groupBox.setFont(font)
        self.groupBox.setObjectName("groupBox")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.gausianPro_Box = QtWidgets.QCheckBox(self.groupBox)
        self.gausianPro_Box.setObjectName("gausianPro_Box")
        self.gridLayout_2.addWidget(self.gausianPro_Box, 6, 0, 1, 1)
        self.extratreeBox = QtWidgets.QCheckBox(self.groupBox)
        self.extratreeBox.setObjectName("extratreeBox")
        self.gridLayout_2.addWidget(self.extratreeBox, 4, 0, 1, 1)
        self.rforoestBox = QtWidgets.QCheckBox(self.groupBox)
        self.rforoestBox.setObjectName("rforoestBox")
        self.gridLayout_2.addWidget(self.rforoestBox, 16, 0, 1, 1)
        self.qdaBox = QtWidgets.QCheckBox(self.groupBox)
        self.qdaBox.setObjectName("qdaBox")
        self.gridLayout_2.addWidget(self.qdaBox, 18, 0, 1, 1)
        self.pasagrBox = QtWidgets.QCheckBox(self.groupBox)
        self.pasagrBox.setObjectName("pasagrBox")
        self.gridLayout_2.addWidget(self.pasagrBox, 15, 0, 1, 1)
        self.bernoulliBox = QtWidgets.QCheckBox(self.groupBox)
        self.bernoulliBox.setObjectName("bernoulliBox")
        self.gridLayout_2.addWidget(self.bernoulliBox, 2, 0, 1, 1)
        self.multinbBox = QtWidgets.QCheckBox(self.groupBox)
        self.multinbBox.setObjectName("multinbBox")
        self.gridLayout_2.addWidget(self.multinbBox, 14, 0, 1, 1)
        self.ldaBox = QtWidgets.QCheckBox(self.groupBox)
        self.ldaBox.setObjectName("ldaBox")
        self.gridLayout_2.addWidget(self.ldaBox, 9, 0, 1, 1)
        self.gaussianBox = QtWidgets.QCheckBox(self.groupBox)
        self.gaussianBox.setObjectName("gaussianBox")
        self.gridLayout_2.addWidget(self.gaussianBox, 5, 0, 1, 1)
        self.adaBox = QtWidgets.QCheckBox(self.groupBox)
        self.adaBox.setObjectName("adaBox")
        self.gridLayout_2.addWidget(self.adaBox, 0, 0, 1, 1)
        self.liblinearBox = QtWidgets.QCheckBox(self.groupBox)
        self.liblinearBox.setObjectName("liblinearBox")
        self.gridLayout_2.addWidget(self.liblinearBox, 10, 0, 1, 1)
        self.libsvmBox = QtWidgets.QCheckBox(self.groupBox)
        self.libsvmBox.setObjectName("libsvmBox")
        self.gridLayout_2.addWidget(self.libsvmBox, 12, 0, 1, 1)
        self.knnBox = QtWidgets.QCheckBox(self.groupBox)
        self.knnBox.setObjectName("knnBox")
        self.gridLayout_2.addWidget(self.knnBox, 8, 0, 1, 1)
        self.gradientBox = QtWidgets.QCheckBox(self.groupBox)
        self.gradientBox.setObjectName("gradientBox")
        self.gridLayout_2.addWidget(self.gradientBox, 7, 0, 1, 1)
        self.sgdBox = QtWidgets.QCheckBox(self.groupBox)
        self.sgdBox.setObjectName("sgdBox")
        self.gridLayout_2.addWidget(self.sgdBox, 17, 0, 1, 1)
        self.dtreeBox = QtWidgets.QCheckBox(self.groupBox)
        self.dtreeBox.setObjectName("dtreeBox")
        self.gridLayout_2.addWidget(self.dtreeBox, 3, 0, 1, 1)
        self.linearsvr_Box = QtWidgets.QCheckBox(self.groupBox)
        self.linearsvr_Box.setObjectName("linearsvr_Box")
        self.gridLayout_2.addWidget(self.linearsvr_Box, 11, 0, 1, 1)
        self.ardBox = QtWidgets.QCheckBox(self.groupBox)
        self.ardBox.setObjectName("ardBox")
        self.gridLayout_2.addWidget(self.ardBox, 1, 0, 1, 1)
        self.libsvrBox = QtWidgets.QCheckBox(self.groupBox)
        self.libsvrBox.setObjectName("libsvrBox")
        self.gridLayout_2.addWidget(self.libsvrBox, 13, 0, 1, 1)
        self.label_25 = QtWidgets.QLabel(self.page_3)
        self.label_25.setGeometry(QtCore.QRect(110, 0, 591, 91))
        font = QtGui.QFont()
        font.setFamily("Serif")
        font.setPointSize(35)
        font.setBold(True)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(75)
        self.label_25.setFont(font)
        self.label_25.setObjectName("label_25")
        self.backButton2 = QtWidgets.QPushButton(self.page_3)
        self.backButton2.setGeometry(QtCore.QRect(0, 500, 91, 31))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.backButton2.setFont(font)
        self.backButton2.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.backButton2.setObjectName("backButton2")
        self.nextButton2 = QtWidgets.QPushButton(self.page_3)
        self.nextButton2.setGeometry(QtCore.QRect(0, 460, 91, 31))
        self.nextButton2.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.nextButton2.setObjectName("nextButton2")
        self.layoutWidget5 = QtWidgets.QWidget(self.page_3)
        self.layoutWidget5.setGeometry(QtCore.QRect(320, 320, 321, 61))
        self.layoutWidget5.setObjectName("layoutWidget5")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.layoutWidget5)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.label_12 = QtWidgets.QLabel(self.layoutWidget5)
        self.label_12.setObjectName("label_12")
        self.horizontalLayout_10.addWidget(self.label_12)
        spacerItem = QtWidgets.QSpacerItem(88, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_10.addItem(spacerItem)
        self.holdout_box = QtWidgets.QDoubleSpinBox(self.layoutWidget5)
        self.holdout_box.setObjectName("holdout_box")
        self.horizontalLayout_10.addWidget(self.holdout_box)
        self.verticalLayout_3.addLayout(self.horizontalLayout_10)
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.label_11 = QtWidgets.QLabel(self.layoutWidget5)
        self.label_11.setObjectName("label_11")
        self.horizontalLayout_9.addWidget(self.label_11)
        spacerItem1 = QtWidgets.QSpacerItem(88, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_9.addItem(spacerItem1)
        self.cvfoldsBox = QtWidgets.QSpinBox(self.layoutWidget5)
        self.cvfoldsBox.setObjectName("cvfoldsBox")
        self.horizontalLayout_9.addWidget(self.cvfoldsBox)
        self.verticalLayout_3.addLayout(self.horizontalLayout_9)
        self.label_16 = QtWidgets.QLabel(self.page_3)
        self.label_16.setGeometry(QtCore.QRect(350, 300, 261, 21))
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.label_16.setFont(font)
        self.label_16.setObjectName("label_16")
        self.layoutWidget6 = QtWidgets.QWidget(self.page_3)
        self.layoutWidget6.setGeometry(QtCore.QRect(320, 450, 210, 77))
        self.layoutWidget6.setObjectName("layoutWidget6")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.layoutWidget6)
        self.verticalLayout_8.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.checkBox_16 = QtWidgets.QCheckBox(self.layoutWidget6)
        self.checkBox_16.setObjectName("checkBox_16")
        self.verticalLayout_8.addWidget(self.checkBox_16)
        self.ensembling_checkbox = QtWidgets.QCheckBox(self.layoutWidget6)
        self.ensembling_checkbox.setObjectName("ensembling_checkbox")
        self.verticalLayout_8.addWidget(self.ensembling_checkbox)
        self.metalearning_checkbox = QtWidgets.QCheckBox(self.layoutWidget6)
        self.metalearning_checkbox.setObjectName("metalearning_checkbox")
        self.verticalLayout_8.addWidget(self.metalearning_checkbox)
        self.layoutWidget7 = QtWidgets.QWidget(self.page_3)
        self.layoutWidget7.setGeometry(QtCore.QRect(320, 120, 321, 58))
        self.layoutWidget7.setObjectName("layoutWidget7")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.layoutWidget7)
        self.horizontalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout()
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.label_4 = QtWidgets.QLabel(self.layoutWidget7)
        self.label_4.setObjectName("label_4")
        self.verticalLayout_6.addWidget(self.label_4)
        self.label_7 = QtWidgets.QLabel(self.layoutWidget7)
        self.label_7.setObjectName("label_7")
        self.verticalLayout_6.addWidget(self.label_7)
        self.horizontalLayout_5.addLayout(self.verticalLayout_6)
        spacerItem2 = QtWidgets.QSpacerItem(118, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem2)
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.timeLeft_box = QtWidgets.QSpinBox(self.layoutWidget7)
        self.timeLeft_box.setObjectName("timeLeft_box")
        self.verticalLayout_5.addWidget(self.timeLeft_box)
        self.perRun_box = QtWidgets.QSpinBox(self.layoutWidget7)
        self.perRun_box.setObjectName("perRun_box")
        self.verticalLayout_5.addWidget(self.perRun_box)
        self.horizontalLayout_5.addLayout(self.verticalLayout_5)
        self.layoutWidget8 = QtWidgets.QWidget(self.page_3)
        self.layoutWidget8.setGeometry(QtCore.QRect(320, 200, 321, 26))
        self.layoutWidget8.setObjectName("layoutWidget8")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.layoutWidget8)
        self.horizontalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label_8 = QtWidgets.QLabel(self.layoutWidget8)
        self.label_8.setObjectName("label_8")
        self.horizontalLayout_6.addWidget(self.label_8)
        spacerItem3 = QtWidgets.QSpacerItem(88, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem3)
        self.memory_box = QtWidgets.QSpinBox(self.layoutWidget8)
        self.memory_box.setObjectName("memory_box")
        self.horizontalLayout_6.addWidget(self.memory_box)
        self.layoutWidget9 = QtWidgets.QWidget(self.page_3)
        self.layoutWidget9.setGeometry(QtCore.QRect(320, 230, 321, 25))
        self.layoutWidget9.setObjectName("layoutWidget9")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.layoutWidget9)
        self.horizontalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.label_9 = QtWidgets.QLabel(self.layoutWidget9)
        self.label_9.setObjectName("label_9")
        self.horizontalLayout_7.addWidget(self.label_9)
        self.ressampleCombo = QtWidgets.QComboBox(self.layoutWidget9)
        self.ressampleCombo.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.ressampleCombo.setObjectName("ressampleCombo")
        self.horizontalLayout_7.addWidget(self.ressampleCombo)
        self.layoutWidget10 = QtWidgets.QWidget(self.page_3)
        self.layoutWidget10.setGeometry(QtCore.QRect(320, 260, 321, 25))
        self.layoutWidget10.setObjectName("layoutWidget10")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout(self.layoutWidget10)
        self.horizontalLayout_8.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.label_10 = QtWidgets.QLabel(self.layoutWidget10)
        self.label_10.setObjectName("label_10")
        self.horizontalLayout_8.addWidget(self.label_10)
        self.metricCombo = QtWidgets.QComboBox(self.layoutWidget10)
        self.metricCombo.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.metricCombo.setObjectName("metricCombo")
        self.horizontalLayout_8.addWidget(self.metricCombo)
        self.label_6 = QtWidgets.QLabel(self.page_3)
        self.label_6.setGeometry(QtCore.QRect(350, 430, 181, 16))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.layoutWidget11 = QtWidgets.QWidget(self.page_3)
        self.layoutWidget11.setGeometry(QtCore.QRect(320, 390, 321, 25))
        self.layoutWidget11.setObjectName("layoutWidget11")
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout(self.layoutWidget11)
        self.horizontalLayout_11.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.label_14 = QtWidgets.QLabel(self.layoutWidget11)
        self.label_14.setObjectName("label_14")
        self.horizontalLayout_11.addWidget(self.label_14)
        spacerItem4 = QtWidgets.QSpacerItem(88, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_11.addItem(spacerItem4)
        self.test_sz_box = QtWidgets.QDoubleSpinBox(self.layoutWidget11)
        self.test_sz_box.setObjectName("test_sz_box")
        self.horizontalLayout_11.addWidget(self.test_sz_box)
        self.savemodel_Box = QtWidgets.QCheckBox(self.page_3)
        self.savemodel_Box.setGeometry(QtCore.QRect(580, 440, 129, 25))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.savemodel_Box.setFont(font)
        self.savemodel_Box.setObjectName("savemodel_Box")
        self.run_Button = QtWidgets.QPushButton(self.page_3)
        self.run_Button.setGeometry(QtCore.QRect(580, 470, 131, 61))
        font = QtGui.QFont()
        font.setFamily("Serif")
        font.setPointSize(25)
        font.setBold(True)
        font.setWeight(75)
        font.setStrikeOut(False)
        self.run_Button.setFont(font)
        self.run_Button.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.run_Button.setObjectName("run_Button")
        self.nextButton2_2 = QtWidgets.QPushButton(self.page_3)
        self.nextButton2_2.setGeometry(QtCore.QRect(10, 30, 91, 31))
        self.nextButton2_2.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.nextButton2_2.setObjectName("nextButton2_2")
        self.hist_btn = QtWidgets.QPushButton(self.page_3)
        self.hist_btn.setGeometry(QtCore.QRect(700, 30, 91, 31))
        self.hist_btn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.hist_btn.setObjectName("hist_btn")
        self.result_text = QtWidgets.QTextEdit(self.page_3)
        self.result_text.setGeometry(QtCore.QRect(500, 550, 291, 31))
        self.result_text.setObjectName("result_text")
        self.stackedWidget.addWidget(self.page_3)
        self.page_4 = QtWidgets.QWidget()
        self.page_4.setObjectName("page_4")
        self.tabWidget = QtWidgets.QTabWidget(self.page_4)
        self.tabWidget.setGeometry(QtCore.QRect(0, 110, 451, 471))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.tabWidget.setFont(font)
        self.tabWidget.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.tab)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.classification_table = QtWidgets.QTableWidget(self.tab)
        self.classification_table.setObjectName("classification_table")
        self.classification_table.setColumnCount(0)
        self.classification_table.setRowCount(0)
        self.gridLayout_4.addWidget(self.classification_table, 0, 0, 1, 1)
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.regression_table = QtWidgets.QTableWidget(self.tab_2)
        self.regression_table.setGeometry(QtCore.QRect(10, 10, 431, 421))
        self.regression_table.setObjectName("regression_table")
        self.regression_table.setColumnCount(0)
        self.regression_table.setRowCount(0)
        self.tabWidget.addTab(self.tab_2, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.ts_table = QtWidgets.QTableWidget(self.tab_3)
        self.ts_table.setGeometry(QtCore.QRect(10, 10, 431, 421))
        self.ts_table.setObjectName("ts_table")
        self.ts_table.setColumnCount(0)
        self.ts_table.setRowCount(0)
        self.tabWidget.addTab(self.tab_3, "")
        self.label_26 = QtWidgets.QLabel(self.page_4)
        self.label_26.setGeometry(QtCore.QRect(170, 0, 471, 91))
        font = QtGui.QFont()
        font.setFamily("Serif")
        font.setPointSize(35)
        font.setBold(True)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(75)
        self.label_26.setFont(font)
        self.label_26.setObjectName("label_26")
        self.home_btn = QtWidgets.QPushButton(self.page_4)
        self.home_btn.setGeometry(QtCore.QRect(60, 30, 71, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.home_btn.setFont(font)
        self.home_btn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.home_btn.setObjectName("home_btn")
        self.layoutWidget12 = QtWidgets.QWidget(self.page_4)
        self.layoutWidget12.setGeometry(QtCore.QRect(460, 110, 341, 471))
        self.layoutWidget12.setObjectName("layoutWidget12")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout(self.layoutWidget12)
        self.verticalLayout_10.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.pushButton_7 = QtWidgets.QPushButton(self.layoutWidget12)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.pushButton_7.setFont(font)
        self.pushButton_7.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_7.setObjectName("pushButton_7")
        self.verticalLayout_2.addWidget(self.pushButton_7)
        self.textEdit_2 = QtWidgets.QTextEdit(self.layoutWidget12)
        self.textEdit_2.setObjectName("textEdit_2")
        self.verticalLayout_2.addWidget(self.textEdit_2)
        self.verticalLayout_10.addLayout(self.verticalLayout_2)
        self.pushButton_9 = QtWidgets.QPushButton(self.layoutWidget12)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.pushButton_9.setFont(font)
        self.pushButton_9.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_9.setObjectName("pushButton_9")
        self.verticalLayout_10.addWidget(self.pushButton_9)
        self.stackedWidget.addWidget(self.page_4)
        self.page_7 = QtWidgets.QWidget()
        self.page_7.setObjectName("page_7")
        self.label_27 = QtWidgets.QLabel(self.page_7)
        self.label_27.setGeometry(QtCore.QRect(100, 0, 591, 91))
        font = QtGui.QFont()
        font.setFamily("Serif")
        font.setPointSize(35)
        font.setBold(True)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(75)
        self.label_27.setFont(font)
        self.label_27.setObjectName("label_27")
        self.label_28 = QtWidgets.QLabel(self.page_7)
        self.label_28.setGeometry(QtCore.QRect(30, 200, 741, 141))
        font = QtGui.QFont()
        font.setFamily("Waree")
        font.setPointSize(50)
        font.setBold(True)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(75)
        self.label_28.setFont(font)
        self.label_28.setObjectName("label_28")
        self.home_btn2_2 = QtWidgets.QPushButton(self.page_7)
        self.home_btn2_2.setGeometry(QtCore.QRect(300, 310, 151, 71))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.home_btn2_2.setFont(font)
        self.home_btn2_2.setObjectName("home_btn2_2")
        self.stackedWidget.addWidget(self.page_7)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.stackedWidget.setCurrentIndex(0)
        self.tabWidget.setCurrentIndex(0)
        self.perRun_box.valueChanged['QString'].connect(self.perrun_Slot)
        self.nextButton.clicked.connect(self.nextSlot)
        self.importButton.clicked.connect(self.importSlot)
        self.timeLeft_box.valueChanged['QString'].connect(self.timeleft_Slot)
        self.comboBox.activated['QString'].connect(self.featureSlot)
        self.browseButton.clicked.connect(self.browseSlot)
        self.cancelButton.clicked.connect(self.cancelSlot)
        self.nextButton2.clicked.connect(self.nextSlot_2)
        self.backButton2.clicked.connect(self.backSlot_1)
        self.memory_box.valueChanged['QString'].connect(self.ensmemory_Slot)
        self.metricCombo.activated['QString'].connect(self.metricBox)
        self.ressampleCombo.activated['QString'].connect(self.resampleBox)
        self.checkBox_16.stateChanged['int'].connect(self.prepro_Checked)
        self.adaBox.stateChanged['int'].connect(self.adaChecked)
        self.groupBox.toggled['bool'].connect(self.select_all_Estimators)
        self.bernoulliBox.stateChanged['int'].connect(self.bernoulliChecked)
        self.dtreeBox.stateChanged['int'].connect(self.dectreeChecked)
        self.extratreeBox.stateChanged['int'].connect(self.extraTreeChecked)
        self.gaussianBox.stateChanged['int'].connect(self.gausianChecked)
        self.gradientBox.stateChanged['int'].connect(self.gradient_checked)
        self.knnBox.stateChanged['int'].connect(self.knnChecked)
        self.ldaBox.stateChanged['int'].connect(self.ldaChecked)
        self.liblinearBox.stateChanged['int'].connect(self.liblinearChecked)
        self.libsvmBox.stateChanged['int'].connect(self.libsvmChecked)
        self.multinbBox.stateChanged['int'].connect(self.multnbChecked)
        self.pasagrBox.stateChanged['int'].connect(self.pasagrChecked)
        self.rforoestBox.stateChanged['int'].connect(self.rforestChecked)
        self.sgdBox.stateChanged['int'].connect(self.sgdChecked)
        self.qdaBox.stateChanged['int'].connect(self.qdaChecked)
        self.cvfoldsBox.valueChanged['QString'].connect(self.cv_Folds)
        self.holdout_box.valueChanged['QString'].connect(self.holdout_Size)
        self.ardBox.stateChanged['int'].connect(self.ard_Checked)
        self.gausianPro_Box.stateChanged['int'].connect(self.gausianPro_Checked)
        self.linearsvr_Box.stateChanged['int'].connect(self.liblinearsvr_Checked)
        self.libsvrBox.stateChanged['int'].connect(self.libsvr_Checked)
        self.backButton1.clicked.connect(self.backSlot)
        self.nextButton1.clicked.connect(self.nextSlot_1)
        self.load_DB_btn.clicked.connect(self.load_DB)
        self.savemodel_Box.stateChanged['int'].connect(self.save_Checked)
        self.showen_btn.clicked.connect(self.show_ensembles)
        self.predict_btn.clicked.connect(self.predict_y)
        self.pushButton_2.clicked.connect(self.fetch_model)
        self.ensembling_checkbox.stateChanged['int'].connect(self.ensembling_checked)
        self.metalearning_checkbox.stateChanged['int'].connect(self.metalearning_checked)
        self.test_sz_box.valueChanged['QString'].connect(self.test_sz_Slot)
        self.run_Button.clicked.connect(self.modelSlot)
        self.home_btn.clicked.connect(self.home_slot)
        self.home_btn2.clicked.connect(self.home_slot)
        self.back_btn.clicked.connect(self.models_back)
        self.get_started_btn.clicked.connect(self.get_started)
        self.history_btn.clicked.connect(self.history_tabs)
        self.radio_btn_c.toggled['bool'].connect(self.radio_c)
        self.radio_btn_r.toggled['bool'].connect(self.radio_r)
        self.radio_btn_ts.toggled['bool'].connect(self.radio_ts)
        self.home_btn2_2.clicked.connect(self.home_slot)
        self.nextButton2_2.clicked.connect(self.home_slot)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        #! extra: 
        self.stackedWidget.setCurrentIndex(0) # Na ksekinaei apo 1h othoni
        self.nextButton.setEnabled(False) # Otan ginei to import me valid file energopoieitai to next button
        self.nextButton1.setEnabled(False) # Otan ginei to import me valid file energopoieitai to next button
        self.load_DB_btn.setEnabled(False)
        self.showen_btn.setEnabled(False)
        self.predict_btn.setEnabled(False)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Auto-ML Tool for IoT Applications"))
        self.label_19.setText(_translate("MainWindow", "WELCOME "))
        self.label_20.setText(_translate("MainWindow", "TO "))
        self.label_21.setText(_translate("MainWindow", "AUTO-ML TOOL"))
        self.pushButton_3.setText(_translate("MainWindow", "About"))
        self.get_started_btn.setText(_translate("MainWindow", "Get Started"))
        self.history_btn.setText(_translate("MainWindow", "Browse Model History"))
        self.nextButton.setText(_translate("MainWindow", "Next"))
        self.label_22.setText(_translate("MainWindow", "IMPORT YOUR DATA"))
        self.home_btn2.setText(_translate("MainWindow", "HOME"))
        self.label.setText(_translate("MainWindow", "Select your CSV File"))
        self.cancelButton.setText(_translate("MainWindow", "Clear"))
        self.importButton.setText(_translate("MainWindow", "Import"))
        self.label_2.setText(_translate("MainWindow", "File Name"))
        self.browseButton.setText(_translate("MainWindow", "Browse"))
        self.radio_btn_c.setText(_translate("MainWindow", "Classification "))
        self.radio_btn_r.setText(_translate("MainWindow", "Regression"))
        self.radio_btn_ts.setText(_translate("MainWindow", "Time-Series"))
        self.label_3.setText(_translate("MainWindow", "Define the Problem Type"))
        self.backButton1.setText(_translate("MainWindow", "Back"))
        self.label_23.setText(_translate("MainWindow", "SELECT YOUR TARGET"))
        self.label_13.setText(_translate("MainWindow", "Summary"))
        self.load_DB_btn.setText(_translate("MainWindow", "LOAD EXISTING MODEL"))
        self.nextButton1.setText(_translate("MainWindow", "CREATE NEW MODEL"))
        self.label_5.setText(_translate("MainWindow", "TARGET"))
        self.back_btn.setText(_translate("MainWindow", "Back"))
        self.label_24.setText(_translate("MainWindow", "MODELS"))
        self.pushButton_2.setText(_translate("MainWindow", "Load Model"))
        self.showen_btn.setText(_translate("MainWindow", "Show Ensembles"))
        self.predict_btn.setText(_translate("MainWindow", "Predict Target"))
        self.label_15.setText(_translate("MainWindow", "Other Parameters"))
        self.groupBox.setTitle(_translate("MainWindow", "Select Estimators: "))
        self.gausianPro_Box.setText(_translate("MainWindow", "gaussian_process"))
        self.extratreeBox.setText(_translate("MainWindow", "extra_trees"))
        self.rforoestBox.setText(_translate("MainWindow", "random_forest"))
        self.qdaBox.setText(_translate("MainWindow", "qda"))
        self.pasagrBox.setText(_translate("MainWindow", "passive_aggressive"))
        self.bernoulliBox.setText(_translate("MainWindow", "bernoulli_nb"))
        self.multinbBox.setText(_translate("MainWindow", "multinomial_nb"))
        self.ldaBox.setText(_translate("MainWindow", "lda"))
        self.gaussianBox.setText(_translate("MainWindow", "gaussian_nb"))
        self.adaBox.setText(_translate("MainWindow", "adaboost"))
        self.liblinearBox.setText(_translate("MainWindow", "liblinear_svc"))
        self.libsvmBox.setText(_translate("MainWindow", "libsvm_svc"))
        self.knnBox.setText(_translate("MainWindow", "k_nearest_neighbors"))
        self.gradientBox.setText(_translate("MainWindow", "gradient_boosting"))
        self.sgdBox.setText(_translate("MainWindow", "sgd"))
        self.dtreeBox.setText(_translate("MainWindow", "decision_tree"))
        self.linearsvr_Box.setText(_translate("MainWindow", "liblinear_svr"))
        self.ardBox.setText(_translate("MainWindow", "ard_regression"))
        self.libsvrBox.setText(_translate("MainWindow", "libsvm_svr"))
        self.label_25.setText(_translate("MainWindow", "PARAMETER TUNING"))
        self.backButton2.setText(_translate("MainWindow", "Back"))
        self.nextButton2.setText(_translate("MainWindow", "INFO"))
        self.label_12.setText(_translate("MainWindow", "Holdout Train Size"))
        self.label_11.setText(_translate("MainWindow", "CV folds"))
        self.label_16.setText(_translate("MainWindow", "Resampling Arguments"))
        self.checkBox_16.setText(_translate("MainWindow", "Disable Feature Preprocessing"))
        self.ensembling_checkbox.setText(_translate("MainWindow", "Disable Ensembling"))
        self.metalearning_checkbox.setText(_translate("MainWindow", "Enable Meta-learning"))
        self.label_4.setText(_translate("MainWindow", "Time left for this task"))
        self.label_7.setText(_translate("MainWindow", "Per run time limit"))
        self.label_8.setText(_translate("MainWindow", "Ensemble memory limit"))
        self.label_9.setText(_translate("MainWindow", "Resampling strategy"))
        self.label_10.setText(_translate("MainWindow", "Metric"))
        self.label_6.setText(_translate("MainWindow", "Other Preferences"))
        self.label_14.setText(_translate("MainWindow", "Set Test Size Split"))
        self.savemodel_Box.setText(_translate("MainWindow", "Save Model"))
        self.run_Button.setText(_translate("MainWindow", "GO"))
        self.nextButton2_2.setText(_translate("MainWindow", "ΗΟΜΕ"))
        self.hist_btn.setText(_translate("MainWindow", "Show History"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "Classification Models"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "Regression Models"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("MainWindow", "Time Series Models"))
        self.label_26.setText(_translate("MainWindow", "MODEL HISTORY"))
        self.home_btn.setText(_translate("MainWindow", "HOME"))
        self.pushButton_7.setText(_translate("MainWindow", "Show Model Summary"))
        self.pushButton_9.setText(_translate("MainWindow", "Show more..."))
        self.label_27.setText(_translate("MainWindow", "TIME - SERIES MODE"))
        self.label_28.setText(_translate("MainWindow", "Under Construction!"))
        self.home_btn2_2.setText(_translate("MainWindow", "HOME"))


